### ISSUE TITLE
[Bug] Application logging failing on deployment infrastructure

### ISSUE THREAD

**Issue by SProjects** [andela/vof-deployment-scripts#3]
**What is the issue?**
Application logs are not showing up in Stackdriver because `google-fluentd` is not being installed successfully onto the VMs. This is happening in packer's `setup.sh` file when the `install_logging_agent` function is called.

**Workaround**
None

**Packer Version**
Packer 1.1.0

**Packer set.up erroring function**
```
install_logging_agent(){
  # This installs the logging agent into the VM
  curl -sSO https://dl.google.com/cloudagents/install-logging-agent.sh
  sudo bash install-logging-agent.sh
}
```

**Debug log output**
```
    googlecompute: ========================================================================
    googlecompute: Starting installation of google-fluentd
    googlecompute: ========================================================================
    googlecompute:
    googlecompute: Installing agents for Debian or Ubuntu.
    googlecompute: OK
    googlecompute: E: Could not get lock /var/lib/dpkg/lock - open (11: Resource temporarily unavailable)
    googlecompute: E: Unable to lock the administration directory (/var/lib/dpkg/), is another process using it?
    googlecompute: dpkg-query: no packages found matching google-fluentd
    googlecompute: Failed to restart google-fluentd.service: Unit google-fluentd.service not found.
    googlecompute: grep: /var/log/google-fluentd/google-fluentd.log: No such file or directory
    googlecompute:
    googlecompute: ========================================================================
    googlecompute: Installation of google-fluentd complete.
    googlecompute:
    googlecompute: Logs from this machine should be visible in the log viewer at:
    googlecompute:   (failed to obtain logs viewer URL from agent log)
    googlecompute:
    googlecompute: A test message has been sent to syslog to help verify proper operation.
    googlecompute:
    googlecompute: Please consult the documentation for troubleshooting advice:
    googlecompute:   https://cloud.google.com/logging/docs/agent
    googlecompute:
    googlecompute: You can monitor the logging agent's logfile at:
    googlecompute:   /var/log/google-fluentd/google-fluentd.log
    googlecompute: ========================================================================
```

**Expected Behavior**
```
googlecompute: ========================================================================
    googlecompute: Starting installation of google-fluentd
    googlecompute: ========================================================================
    googlecompute:
    googlecompute: Installing agents for Debian or Ubuntu.
    googlecompute: OK
    googlecompute: Selecting previously unselected package google-fluentd.
    googlecompute: (Reading database ... 69625 files and directories currently installed.)
    googlecompute: Preparing to unpack .../google-fluentd_1.5.23-1_amd64.deb ...
    googlecompute: Unpacking google-fluentd (1.5.23-1) ...
    googlecompute: Selecting previously unselected package google-fluentd-catch-all-config.
    googlecompute: Preparing to unpack .../google-fluentd-catch-all-config_0.6_all.deb ...
    googlecompute: Unpacking google-fluentd-catch-all-config (0.6) ...
    googlecompute: Setting up google-fluentd (1.5.23-1) ...
    googlecompute: Adding system user `google-fluentd' (UID 114) ...
    googlecompute: Adding new group `google-fluentd' (GID 119) ...
    googlecompute: Adding new user `google-fluentd' (UID 114) with group `google-fluentd' ...
    googlecompute: Not creating home directory `/home/google-fluentd'.
    googlecompute: Installing default conffile /etc/google-fluentd/google-fluentd.conf ...
    googlecompute: Setting up google-fluentd-catch-all-config (0.6) ...
    googlecompute: Processing triggers for libc-bin (2.23-0ubuntu9) ...
    googlecompute:
    googlecompute: =======================================================================
    googlecompute: Installation of google-fluentd complete.
    googlecompute:
    googlecompute: Logs from this machine should be visible in the log viewer at:
    googlecompute:   https://console.cloud.google.com/logs/viewer?project=vof-migration-test&resource=gce_instance/instance_id/8975740949397196963
    googlecompute:
    googlecompute: A test message has been sent to syslog to help verify proper operation.
    googlecompute:
    googlecompute: Please consult the documentation for troubleshooting advice:
    googlecompute:   https://cloud.google.com/logging/docs/agent
    googlecompute:
    googlecompute: You can monitor the logging agent's logfile at:
    googlecompute:   /var/log/google-fluentd/google-fluentd.log
    googlecompute: =======================================================================
```

**Steps to reproduce**
```
cd path/to/packer/folder
packer build packer.json
```
